## LU Factorization

In [40]:
using LinearAlgebra
A = [4 4 1; 2 4 1; -3 1 2]
b= [4 3 -13]'

F = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
  1.0   0.0  0.0
 -0.75  1.0  0.0
  0.5   0.5  1.0
U factor:
3×3 Matrix{Float64}:
 4.0  4.0   1.0
 0.0  4.0   2.75
 0.0  0.0  -0.875

In [7]:
L = F.L
U = F.U

Y = L\b

3×1 Matrix{Float64}:
   4.0
   6.0
 -18.0

## cholesky

In [52]:
symmetric positive definiteness

3.0

## Normal equation/ Cholesky

In [46]:
## Write a function in Julia that solve LSQ problem by using the normal equation
A = [1 3 1; 1 3 7; 1 -1 -4; 1 -1 2]
b = [1 1 1 1]'
function least_square_problem(A,b)
    B = A'*A
    bhat = A'*b
    R = cholesky(B)
    y
    = R'\bhat
    x = R\y
    
    return x
end

LoadError: ParseError:
# Error @ ]8;;file:///home/guest/Downloads/In[46]#9:5\In[46]:9:5]8;;\
    y
    = R'\bhat
#   ╙ ── unexpected `=`

In [47]:

B = A'*A
F = cholesky(B)
R = F.U
bhat =A'*b
y = R'\bhat
x = R\y
A

4×3 Matrix{Int64}:
 1   3   1
 1   3   7
 1  -1  -4
 1  -1   2

In [36]:
R = cholesky(B)

Cholesky{Float64, Matrix{Float64}}
U factor:
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 5.38516  3.8996   0.0
  ⋅       4.21819  2.37069
  ⋅        ⋅       0.616316

In [37]:
C = collect(R.U)

3×3 Matrix{Float64}:
 5.38516  3.8996   0.0
 0.0      4.21819  2.37069
 0.0      0.0      0.616316

In [43]:
least_square_problem(A,b)

3×1 Matrix{Float64}:
  0.31423611111111116
 -0.05381944444444445
 -0.006944444444444444

## QR Decomposition

In [41]:
## RQ Decomposition
#Ax = b
a = 1/sqrt(2)
Q= [1/sqrt(2) 1/sqrt(2); 1/sqrt(2) 1/sqrt(2); 0 0]
b = [1 1 1]'

R = [1 1; 0 1]

Q*R

display(Q\b)
display(Q'b)
# F = qr(A)
# R = display(F.R)
R = collect(F.R)

2×1 Matrix{Float64}:
 0.7071067811865477
 0.7071067811865475

2×1 Matrix{Float64}:
 1.414213562373095
 1.414213562373095

LoadError: FieldError: type LU has no field `R`, available fields: `factors`, `ipiv`, `info`
Available properties: `L`, `U`, `p`, `P`

In [45]:
A

2×2 Matrix{Int64}:
 1  2
 3  4

In [46]:
?norm

search: norm norm1 nor opnorm for normpath xor rm sort Core inf_norm



```julia
norm(A, p::Real=2)
```

For any iterable container `A` (including arrays of any dimension) of numbers (or any element type for which `norm` is defined), compute the `p`-norm (defaulting to `p=2`) as if `A` were a vector of the corresponding length.

The `p`-norm is defined as

$$
\|A\|_p = \left( \sum_{i=1}^n | a_i | ^p \right)^{1/p}
$$

with $a_i$ the entries of $A$, $| a_i |$ the [`norm`](@ref) of $a_i$, and $n$ the length of $A$. Since the `p`-norm is computed using the [`norm`](@ref)s of the entries of `A`, the `p`-norm of a vector of vectors is not compatible with the interpretation of it as a block vector in general if `p != 2`.

`p` can assume any numeric value (even though not all values produce a mathematically valid vector norm). In particular, `norm(A, Inf)` returns the largest value in `abs.(A)`, whereas `norm(A, -Inf)` returns the smallest. If `A` is a matrix and `p=2`, then this is equivalent to the Frobenius norm.

The second argument `p` is not necessarily a part of the interface for `norm`, i.e. a custom type may only implement `norm(A)` without second argument.

Use [`opnorm`](@ref) to compute the operator norm of a matrix.

# Examples

```jldoctest
julia> v = [3, -2, 6]
3-element Vector{Int64}:
  3
 -2
  6

julia> norm(v)
7.0

julia> norm(v, 1)
11.0

julia> norm(v, Inf)
6.0

julia> norm([1 2 3; 4 5 6; 7 8 9])
16.881943016134134

julia> norm([1 2 3 4 5 6 7 8 9])
16.881943016134134

julia> norm(1:9)
16.881943016134134

julia> norm(hcat(v,v), 1) == norm(vcat(v,v), 1) != norm([v,v], 1)
true

julia> norm(hcat(v,v), 2) == norm(vcat(v,v), 2) == norm([v,v], 2)
true

julia> norm(hcat(v,v), Inf) == norm(vcat(v,v), Inf) != norm([v,v], Inf)
true
```

---

```julia
norm(x::Number, p::Real=2)
```

For numbers, return $\left( |x|^p \right)^{1/p}$.

# Examples

```jldoctest
julia> norm(2, 1)
2.0

julia> norm(-2, 1)
2.0

julia> norm(2, 2)
2.0

julia> norm(-2, 2)
2.0

julia> norm(2, Inf)
2.0

julia> norm(-2, Inf)
2.0
```


In [43]:
sqrt(30)

5.477225575051661

## Factorizzation

In [27]:
### Factorizzation

Q = Matrix(F.Q)

4×3 Matrix{Float64}:
 -0.5  -0.5   0.5
 -0.5  -0.5  -0.5
 -0.5   0.5   0.5
 -0.5   0.5  -0.5

In [28]:
Ro =[F.R;zeros]

4×3 Matrix{Float64}:
 -2.0  -2.0  -3.0
  0.0  -4.0  -5.0
  0.0   0.0  -6.0
  0.0   0.0   0.0

In [17]:
zeros= [0 0 0] ## How to add zeros

1×3 Matrix{Int64}:
 0  0  0

## SVD 

In [70]:
F = svd(A)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
4×3 Matrix{Float64}:
 -0.241309   0.817716   -0.152022
 -0.849048   0.0237597  -0.168977
  0.438432   0.30868    -0.680069
 -0.169306  -0.485276   -0.697024
singular values:
3-element Vector{Float64}:
 9.039685945310081
 3.037928933460727
 1.7478746538025831
Vt factor:
3×3 Matrix{Float64}:
 -0.0908473  -0.391628  -0.915628
  0.218859    0.8891    -0.401997
 -0.971518    0.236914  -0.00493921

In [78]:
x = F.V'
Y = F.U
z = F.S'

X = x*y*z

3×3 Matrix{Float64}:
  -1.64246  -0.551975  -0.317579
   3.95684   1.32976    0.765077
 -17.5644   -5.90281   -3.39618

# Given Decomposition

In [48]:
A = [1 2; 1 3]
b = [1 2]'

H = [1 1]'

2×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 1

In [18]:
cs = H[1]/ sqrt((H[1])^2 + (H[2])^2)

0.7071067811865475

In [20]:
sn = H[2]/ sqrt((H[1])^2 + (H[2])^2)

0.7071067811865475

In [25]:
A[2][1]

1

In [21]:
Q =[cs -sn; cs sn]

2×2 Matrix{Float64}:
 0.707107  -0.707107
 0.707107   0.707107

In [22]:
R = Q'*A

2×2 Matrix{Float64}:
 1.41421  3.53553
 0.0      0.707107

In [23]:
Y = Q\b

2×1 Matrix{Float64}:
 2.121320343559643
 0.7071067811865476

In [24]:
X = R\Y

2×1 Matrix{Float64}:
 -1.0000000000000002
  1.0000000000000002

## House holder

In [76]:
x = [2 -1 1]'

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
  2
 -1
  1

In [78]:
M1 = norm(x,2)

2.449489742783178

In [80]:
e = [1 0 0]'
y = M1*e

3×1 Matrix{Float64}:
 2.449489742783178
 0.0
 0.0

In [81]:
u = x - y

3×1 Matrix{Float64}:
 -0.4494897427831779
 -1.0
  1.0

In [82]:
# Normalizing u

v = u/norm(u)

3×1 Matrix{Float64}:
 -0.3029054465276861
 -0.6738873386790493
  0.6738873386790493

In [83]:
gamma = 2/(norm(u))^2

0.9082482904638632

In [84]:
I = [1 0 0; 0 1 0; 0 0 1]

3×3 Matrix{Int64}:
 1  0  0
 0  1  0
 0  0  1

In [87]:
@time Q = I - (v*v'*gamma)

  0.000030 seconds (49 allocations: 2.359 KiB)


3×3 Matrix{Float64}:
  0.916667  -0.185395  0.185395
 -0.185395   0.587543  0.412457
  0.185395   0.412457  0.587543

In [86]:
Q*x

3×1 Matrix{Float64}:
  2.204124145231932
 -0.545875854768068
  0.545875854768068

## calculating time

In [30]:
A =[1 2; 1 3]

b = [1 2]'


1×2 Matrix{Int64}:
 1  2